name: "Build & Release"   # You can name it as you want

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main


jobs:  # Telling what jobs we need to happen
  build:      # Specify the building name and machine
    name: Build & Release  # you can name the build whatever you want
    runs-on: ubuntu-latest
    steps: 
    # Checkout Repo
    - name: Checkout Repo
      uses: actions/checkout@v3

    #Setup Java
    - name: Setup Jave
      uses: actions/setup-java@3.12.
      with:
        distribution: "oracle"
        java-version: "17"
    